### PR TITLE
Request adding norwegian locale

### PR DESCRIPTION
**Pull request by Baktus79**
Translated to Norwegian Bokmål

### CODE REVIEW

**Comment by Baktus79** [comment]
I see that I got the language code wrong, it should have been nb_NO.

**Comment by xou816** [comment]
Hi! Thank you for your contribution :) if you wish, you can import your translations into the public POEditor project here. https://poeditor.com/join/project?hash=xfVrpQfRBM

In order for the transation to be added, you'll have to add the language code nb_NO to the LINGUAS file as well :) 

Oh and there was a little issue with master, do you mind rebasing/merging master in your branch so that the CI can run? Thanks!

**Comment by Baktus79** [comment]
Hey
I added the locale file to the public POEditor project. As it is now at the public POEditor, do you still want me to create a PR for the file change and for adding the po file? Or how does this work? :)

**Comment by xou816** [comment]
The edit to LINGUAS to edit is still needed, and you can reexport the updated po from POEditor and add it here if you want, or I'll do an export later, whichever you prefer :)

**Comment by xou816** [comment]
actually I'll add it, I'm in the process of updating the others as well anyway :)

**Comment by xou816** [comment]
Thanks for adding them to POEditor!

**Comment by Baktus79** [comment]
No problem, glad I could help :smile:

**Pull request closed without merging**
