### PR TITLE
Add further meson dependency checks

### PR DESCRIPTION
**Pull request by ntonnaett**
I ran into missing openssl in the build stage, so I added some further dependency checks. Is alsa a required dependency?

### CODE REVIEW

**Comment by xou816** [comment]
Hi! Thanks for your contribution! :)
Yes, both PulseAudio and Alsa are required for simplicity, although with some tweaking it should be possible to not depend on PulseAudio.

I'm not super familiar with meson, first project with it; is it customary to list dependencies exhaustively? If that's the case there are probably a few others, such as libcurl.

**Comment by ntonnaett** [comment]
I'm only familiar with using Meson in C++ projects. There you need those dependency objects to get all the information for the compiler and linker. I think it's like the dependencies in Cargo.toml. You only add the direct dependencies. In the perfect world spot would depend on the things specified in Cargo.toml and those crates would depend on the actual C libraries. But when meson doesn't have those deep dependencies cargo-build breaks when those dependencies are missing.

So this PR adds those checks at the setup stage, so you see what dependencies are missing at the first stage with a clear output what's missing. Another advantage is that you can specify the minimum version of the libraries. If there are libraries that are required I would add them to the list.

Hopefully rust support in meson improves fast. Version 0.57 added native cargo test support. It's a beginning.

**Comment by ntonnaett** [comment]
CI build fails, when adding the libcurl dependency. So it seems spot doesn't depend on libcurl headers. I will remove it again.
Are there other potential candidates?

**Comment by xou816** [comment]
My bad, you're right, isahc statically links curl :o 

Thanks for the additional info too, looking forward to seeing better rust support in meson!

So, ldd gives me this:
```
linux-vdso.so.1
libpulse.so.0
libpulse-simple.so.0
libasound.so.2
libhandy-1.so.0
libgtk-3.so.0
libgdk-3.so.0
libz.so.1
libpango-1.0.so.0
libcairo-gobject.so.2
libcairo.so.2
libgdk_pixbuf-2.0.so.0
libgio-2.0.so.0
libgobject-2.0.so.0
libglib-2.0.so.0
libssl.so.1.1
libcrypto.so.1.1
libgcc_s.so.1
libc.so.6
libm.so.6
librt.so.1
libpthread.so.0
libdl.so.2
libpulsecommon-14.2.so
libdbus-1.so.3
libfribidi.so.0
libatk-1.0.so.0
libgmodule-2.0.so.0
libpangocairo-1.0.so.0
libharfbuzz.so.0
libpangoft2-1.0.so.0
libfontconfig.so.1
libfreetype.so.6
libepoxy.so.0
libXi.so.6
libX11.so.6
libatk-bridge-2.0.so.0
libcloudproviders.so.0
libXfixes.so.3
libxkbcommon.so.0
libwayland-client.so.0
libwayland-cursor.so.0
libwayland-egl.so.1
libXext.so.6
libXcursor.so.1
libXdamage.so.1
libXcomposite.so.1
libXrandr.so.2
libXinerama.so.1
libthai.so.0
libpng16.so.16
libXrender.so.1
libxcb.so.1
libxcb-render.so.0the gtk/glib
libxcb-shm.so.0
libpixman-1.so.0
libmount.so.1
libresolv.so.2
libffi.so.7
libpcre.so.1
libsndfile.so.1
libsystemd.so.0
libasyncns.so.0
libgraphite2.so.3
libexpat.so.1
libbz2.so.1.0
libatspi.so.0
libdatrie.so.1
libXau.so.6
libXdmcp.so.6
libblkid.so.1
libvorbisenc.so.2
libFLAC.so.8
libopus.so.0
libvorbis.so.0
libogg.so.0
liblzma.so.5
libzstd.so.1
liblz4.so.1
libcap.so.2
libgcrypt.so.20
libgpg-error.so.0
```

and similarly rustc gives me:

```
"-lpulse" "-lpulse-simple" "-lasound" "-lhandy-1" "-lgtk-3" "-lgdk-3" "-lz" "-lpangocairo-1.0" "-lpango-1.0" "-lharfbuzz" "-latk-1.0" "-lcairo-gobject" "-lcairo" "-lgdk_pixbuf-2.0" "-lgio-2.0" "-lgobject-2.0" "-lglib-2.0" "-lssl" "-lcrypto" "-lz" "-lgtk-3" "-lgdk-3" "-lz" "-lpangocairo-1.0" "-lpango-1.0" "-lharfbuzz" "-latk-1.0" "-lcairo-gobject" "-lcairo" "-lgdk_pixbuf-2.0" "-lgio-2.0" "-lgobject-2.0" "-lglib-2.0" "-latk-1.0" "-lgobject-2.0" "-lglib-2.0" "-lgdk-3" "-lz" "-lpangocairo-1.0" "-lpango-1.0" "-lharfbuzz" "-lgdk_pixbuf-2.0" "-lcairo-gobject" "-lcairo" "-lgobject-2.0" "-lglib-2.0" "-lpango-1.0" "-lgobject-2.0" "-lglib-2.0" "-lharfbuzz" "-lgdk_pixbuf-2.0" "-lgobject-2.0" "-lglib-2.0" "-lcairo-gobject" "-lgobject-2.0" "-lglib-2.0" "-lcairo" "-lgio-2.0" "-lgobject-2.0" "-lglib-2.0" "-lgobject-2.0" "-lglib-2.0" "-lglib-2.0" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
```

I suppose the glib/gtk stack implies a lot of these dependencies, same with pulse/alsa.

Would you mind adding gtk and glib? I suppose that would cover most dependencies?

**Comment by xou816** [comment]
Perfect, thanks! :)

**Pull request merged**
