### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sigaloid**
https://pastebin.com/raw/7f8QHPVg

### CODE REVIEW

**Comment by sigaloid** [comment]
Odd. Running tests after reverting the test.

**Comment by sigaloid** [comment]
Double odd. Passes tests when I revert. Updating Isahc to 1.4.1 seems to trigger it according to the actions log.

**Comment by sigaloid** [comment]
Ok [cargo update](https://lib.rs/crates/cargo-update) does not feel like cooperating and mangling with the Cargo.lock still doesn't pass tests. Plus it seems like you have a dependency bot, so for now closing.

**Comment by xou816** [comment]
Hmm, interesting, I thought dependabot would take care of these but actually not! Might be worth digging into it, I tried it locally and there were compilation errors -- problems for later :D

**Comment by xou816** [comment]
zbus seems to break a few things (expected, 2.x is in beta), the rest should be safe

I should also change the libadwaita dependency to allow newer versions as well

**Comment by sigaloid** [comment]
Hm, should I attempt undoing that dependency in cargo.lock? I wish cargo update had a --exclude option, instead of manually fudging around with Cargo.lock which is hardly good practice AFAIK.

**Comment by xou816** [comment]
As you want, no emergencies here :) but yeah agreed wish there was that!

**Comment by xou816** [comment]
Ah and if you do -- you might have to run `ninja cargo-sources.json -C target` so that the cargo-sources.json file (which is used to prefetch the crates) is up to do date!

**Pull request closed without merging**
