### PR TITLE
Added info about Caps Lock in login screen

### PR DESCRIPTION
**Pull request by przebor**
Hello 👋 
I saw that there's no info about "Caps Lock being enabled" on Spot login screen, so...
I implemented it.

Please let me know if something's wrong with my code (I hope not haha)

### CODE REVIEW

**Comment by xou816** [comment]
Hi! This looks absolutely fine, thank you for your contribution!! :) I merely have one question atm: is the explicit dependency on gdk4-sys needed? can we work around that by updating our version of gdk4?

**Comment by przebor** [comment]
Ohh i just realized we don't need that.
Is was using gdk4-sys to check caps lock state but it was unsafe so I did it other way and forgot about adding it there.
When I get back to my PC, I will remove the dependency.

**Comment by przebor** [comment]
Removed `gdk4-sys` from `Cargo.toml` and `cargo-sources.json` and squashed commits.
Should be fine now.

**Comment by przebor** [comment]
Should be fine now :)

**Comment by xou816** [comment]
Perfect, thanks!! merging this :)

**Pull request merged**
