### PR TITLE
initial support for i18n

### PR DESCRIPTION
**Pull request by xou816**

### CODE REVIEW

**Comment by xou816** [comment]
closes #53

**Comment by daPhipz** [comment]
When this PR gets merged:
Should translations be contributed directly to this repo or are they managed via Damned Lies, the GNOME Translation Project?

**Comment by xou816** [comment]
Glad to see someone already willing to contribute! :o 

Is Damned Lies open to 3rd party softwares? I am under the impression it is not.

Either way, I'm just getting started with GNU gettext, I'd prefer simple pull requests for now while I get used to it :p

**Comment by daPhipz** [comment]
Thanks for the appreciation ;)

Yes, there is a section for 3rd party software in DL. I'm not sure if it is a hard requirement to host the repo on GNOME's GitLab instance though...

If you are willing to try it, feel free to contact the [l18n mailing list](https://mail.gnome.org/mailman/listinfo/gnome-i18n)!

**Pull request merged**
