### PR TITLE
GSettings

### PR DESCRIPTION
**Pull request by xou816**
@exciteabletom

see #139 and #130

### CODE REVIEW

**Comment by exciteabletom** [comment]
All the options are working great on my machine, thanks for adding this :)

My only suggestion would be to have a GUI for changing the settings within Spot, but maybe that's a different PR entirely.

**Comment by xou816** [comment]
Thanks! Glad it works as intended :)

Yeah, I'll add a GUI, most likely later indeed!

**Comment by LennyPenny** [comment]
how do I use this? I tried to use the `gsettings` cli but I can't figure out what set of options to give it to change the bitrate for example. 

I also tried to use `dconf-editor` but the spot settings are nowhere to be found
I'm using the flatpak version btw

**Comment by exciteabletom** [comment]
@LennyPenny 
Use `gsettings list-keys dev.alextren.Spot` to list all the options then use `gsettings set dev.alextren.Spot {option} {value}` to set an option.

So to set the bitrate to maximum would be `gsettings set dev.alextren.Spot player-bitrate 320`

**Comment by xou816** [comment]
@exciteabletom thanks for the clarification :)

Also if you're using the flatpak'd version @LennyPenny you'll have to run the above commands from a sandboxed shell:

```
flatpak run --command=sh dev.alextren.Spot
gsettings list-keys dev.alextren.Spot
```

**Comment by LennyPenny** [comment]
aah ok thx it was not clear to me that it works differently in the flatpak version
(maybe its worth mentioning that in the readme)

**Pull request merged**
