### PR TITLE
basic connect implementation

### PR DESCRIPTION
**Pull request by Ella-0**
Adds a basic spotify connect implementation closing #55 

TODO:
 - [ ] Switching between devices
 - [ ] Selecting connect device
 - [ ] Handle end of track etc

### CODE REVIEW

**Comment by xou816** [comment]
Looking good so far! :) Just a quick remark (...from what I can see on a phone...), I'd rather have the player part focus on being the interface that connects spot to librespot, and keep the connect stuff out of here. Ideally, we'd have two different services (local and connect) both handling the same Command enum or both being hidden being the same trait, and we'd control one, or the other, or both sometimes. Hope this makes sense!

**Comment by xou816** [comment]
(I won't do the in depth review so far since it's WIP but tell me if you want more feedback anyway!)

**Comment by jannuary** [comment]
Any update? :)

**Comment by Ella-0** [comment]
Busy with school stuff at the moment but haven't forgotten about it.

**Comment by jannuary** [comment]
Alright, take your time!

**Comment by xou816** [comment]
No worries indeed!!

Actually, I want to help out, I'll pick up where you left off and continue when I have time as well!

(branch for now: https://github.com/xou816/spot/tree/Ella-0-basic-connect-implementation feel free to target it)

**Comment by xou816** [comment]
superseded by #427 feel free to modify

**Pull request closed without merging**
