### PR TITLE
Added translator

### PR DESCRIPTION
**Pull request by walthersmith**
update  Spanish translations on poeditor

### CODE REVIEW

**Comment by Diegovsky** [comment]
Hey there! Are you wiling to be a translator for the project or have you already contributed translations?

**Comment by walthersmith** [comment]
Hello! Yes, I've already made some translations on Poeditor for the Spanish language. I'd be more than willing to continue contributing as a translator for the project. Please let me know if there's anything specific you need help with.

**Comment by Diegovsky** [comment]
Thank you very much! Yes, we'd love more contributions from you. I'm accepting this PR :)

**Review by Diegovsky — APPROVED** [review]

**Comment by Diegovsky** [comment]
... but it takes someone with write access and the original creator seems to be on hiatus right now...

**Comment by Diegovsky** [comment]
Pushed this to my fork of the project. See [this](https://github.com/xou816/spot/issues/591#issuecomment-1895880929) for more information.

Thank you for your contribution :)

**Pull request closed without merging**
