### PR TITLE
icon: new spotlight metaphor, add symbolic, add source file

### PR DESCRIPTION
**Pull request by bertob**
This adds a new app icon, as discussed in #481. I just replaced the assets in this MR, so the build system needs adjusting in a followup.

image

### CODE REVIEW

**Comment by xou816** [comment]
Hi! Again, this looks so much better than the existing icon, thanks a lot! I like how the symbolic icon gives another take on that metaphor too :)

As for the build system adaptation: do you mean we should rasterize the svg as part of the build process? I'm guessing standard tools exist for that?

**Comment by bertob** [comment]
No, you don't need to rasterize it, standard practice is to just use the SVG.

**Comment by xou816** [comment]
Oh okay so it's just a matter of putting files in the right folders then I suppose :)

**Comment by bertob** [comment]
I think the file paths in the data folder don't really matter, it's mostly a matter of adjusting the gresource/build system stuff. Not really my area of expertise though :)

**Comment by Toorero** [comment]
Just execute this in the git root, and it works flawlessly no need to adjust the build system.
```
mkdir -p data/hicolor/scalable/apps
mv data/dev.alextren.Spot.svg data/hicolor/scalable/apps
```

The other option would be (as you suggested) to adjust the build system. For inspiration, you could use [Newsflash](https://gitlab.com/news-flash/news_flash_gtk/-/tree/master/data/icons), but I think that's unnecessary. Just move it.

**Comment by xou816** [comment]
Hi! Yes, indeed, thanks @Toorero !

The build system already installs the hicolor directory: https://github.com/xou816/spot/blob/development/data/meson.build#L6

So indeed moving data/dev.alextren.Spot.svg to  data/hicolor/scalable/apps should be enough

And the symbolic icon should be in data/hicolor/symbolic/apps I think

**Comment by xou816** [comment]
I  took the liberty to move the files as mentioned, and merged :) thanks a lot!

**Pull request merged**
