### PR TITLE
Large seekbar above bottom controls

### PR DESCRIPTION
**Pull request by xou816**
As per @szbergeron suggestion, a seekbar above the bottom controls

I think I like how it looks, especially on mobile :) what do you think @Douile?

Capture d’écran du 2021-03-02 18-54-37

### CODE REVIEW

**Comment by Douile** [comment]
> As per @szbergeron suggestion, a seekbar above the bottom controls
> 
> I think I like how it looks, especially on mobile :) what do you think @Douile?
> 
> Capture d’écran du 2021-03-02 18-54-37

I like it

**Comment by Douile** [comment]
@xou816 did you remove the shuffle button intentionally?

**Comment by xou816** [comment]
Moved it to Now playing, I intend to add more queue control related controls here as well :)

**Comment by Douile** [comment]
ahhh, okay that makes sense

**Pull request merged**
