### PR TITLE
update album view

### PR DESCRIPTION
**Pull request by jannuary**
- Use .card for album cover
- Remove custom styles
- Rework hover 
- Make entire thing clickable
image

### CODE REVIEW

**Comment by xou816** [comment]
I quite liked the old hover effect, maybe we could have both? :blush: 

Nice work otherwise, makes sense to make the whole thing clickable.

spacing_card

The spacing around the image seems a bit inconsistent to me on hover, and maybe the corner radii should match?

**Comment by xou816** [comment]
oh right :( my bad! 

we still can probably do something about it, if we add a container around the button, so that the container grows but the button is centered within it

**Comment by jannuary** [comment]
Should be better now.

**Comment by xou816** [comment]
oh it is much better indeed! LGTM, merging if you're good to go on your end?

**Comment by jannuary** [comment]
Yeah, should be fine to merge.

**Pull request merged**
